### ISSUE TITLE
Provide option to use arrays instead of objects for certain fields

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#10]
From Alex:

...wondering if we can use an array for all of the ['und'] values.

```
[121] pry(main)> School.where(slug: 'c-r-smith-pre-kindergarten-academy').first.ecs.field_ec_special
=> {"und"=>
  {"5123"=>{"tid"=>"5123", "name"=>"add/adhd"},
    "5124"=>{"tid"=>"5124", "name"=>"allergies"},
     "5125"=>{"tid"=>"5125", "name"=>"asthma"},
     "5132"=>{"tid"=>"5132", "name"=>"learning disability"},
     "5133"=>{"tid"=>"5133", "name"=>"speech impairment"}}}
```

Results like that are pretty hard to use when you want to get all of the names together in one string. It'd be a little easier if it was "und" => [{"tid"=>"5123", "name"=>"add/adhd"}, {"tid"=>"5124", "name"=>"allergies"}] without the extra hierarchy in there.

**Comment by uniosx** [comment]
Would it be possible to get rid of the "und" level as well? Could that be a query param too?

**Comment by bnchdrff** [comment]
Yes! #11

**Comment by bnchdrff** [comment]
the flatten_fields option converts taxonomy output to arrays -- see #11 for more deets & related commits.
