### ISSUE TITLE
Add k12 supplemental dataset

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#21]
https://drive.google.com/drive/folders/0B7QdNmEHvwalNUpIOWU2ckVaVmM/0B7QdNmEHvwalflN1Q1pZd0xNM0I4QXNQYlFRYmVYdmo2bTVHSEtkTmtrQ1hsRXVaSE1nNGc/0B9LDi9SHMwnrRjF3WTNGcWRvRWc/0B9LDi9SHMwnrfmExUTQ4SVhjSENpaXhzekFQaWV3Q0hHSFhKLTFoSG9VajkwU0dDb0JvalU

**Comment by bnchdrff** [comment]
Do I need to add the Schools sheet only? Should I add the Mackinac data as well? Same table or a different one?

**Comment by bnchdrff** [comment]
@anderoy that last q's for u!

**Comment by anderoy** [comment]
Just the data sheet. Ignore the mackinac and greatschools (the important info is already included in the data (schools) sheet. Thanks.

**Comment by bnchdrff** [comment]
thanks!

**Comment by bnchdrff** [comment]
i put the normalized data here: https://docs.google.com/spreadsheets/d/1nJoNjvqcOypqOJXPGEQiPynGvUISNTixvibd4BvxRdU/edit#gid=1487136819

schema defined & ready to go... can't create table quite yet though due to mysql syntax error. investigating.

**Comment by bnchdrff** [comment]
pushed to live & uploaded the data

will be available via api as soon as Alec ok's my other api changes!
