### ISSUE TITLE
Build prototype of e3 system

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#28]
notes here: https://docs.google.com/document/d/1_tApwQ24lR0xwd0kbgFjqIKfT9eePxWycD2mE27gOnA/edit

**Comment by bnchdrff** [comment]
@anderoy I started to define as best as I can how the system might work here: https://docs.google.com/document/d/1_tApwQ24lR0xwd0kbgFjqIKfT9eePxWycD2mE27gOnA/edit#

There are many open questions that we should address before I build anything.

**Comment by anderoy** [comment]
I will get to this and answer the questions in the doc when I get a chance. Busy week in and out of the office.

**Comment by anderoy** [comment]
I don't know how this looks to you, but I use ZenHub to manage project boards directly in GitHub (I recommend you checking it out). I moved this to "Done" since we have moved the prototyping to issue 29.
