### ISSUE TITLE
Add early childhood record keeping system

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#3]
Akin to the school / school profile system, set up a taxonomy for early childhood centers and associated entities (profiles, test results, etc).

Why so complicated? In anticipation of eventually allowing early childhood centers to edit their profiles!

- [x] create `ec` taxonomy bundle entity type
- [x] populate `ec` type with obvious perennial fields as found in `earlychild` data table columns
- [x] add county to addressfield via ctools plugin
- [x] create `ec_profile` node bundle entity type
- [x] populate `ec_profile` type with obvious non-perennial fields as found in `earlychild` data table columns
- [x] provide client with each type to review & make changes to each types' fields -- also, if some fields in `earlychild` weren't used, make note of them for review
- [x] after finalizing fields in both types, write migrate routine to move content from `earlychild` table into `ec` and `ec_profile` entities

**Comment by bnchdrff** [comment]
- got final specs for `ec` and `ec_profile` via [Earlychild Dataset Transition data dictionary](https://docs.google.com/spreadsheets/d/1smYR13Ge7YSMgPBoLrfQn3nG2wNA8kKeT5m-x8ITVoA/edit#gid=0)
- implemented in esdet/esdportal_str & documented all finalized fields in sheet (also, added type column)
- pushed changes to [2015scorecard dev site](https://2015scorecard-3mhev6qb5ihtc.us.platform.sh/)

@anderoy please review final fields & then i'll start work on the data migrations!

there are a few notes in the data dictionary about new taxonomies & other things... we can talk more here & there.

**Comment by bnchdrff** [comment]
note: i haven't implemented the `rating` data table yet! working on `ec` and `ec_profile` first.

**Comment by anderoy** [comment]
@anderoy/ESD to-do before @bnchdrff finishes up:
- [x] Review existing fields as they shift to 'ec' and 'ec_profile'
- [x] Create list of new fields to add
- [ ] Get feedback from ESD team
- [ ] Add new fields as vocabularies and add to 'ec_profile'

**Comment by anderoy** [comment]
## Additional notes for Migration
- Most recent data from Great Start found in "GS Export 4/6" tab of google sheet
- Fixed the pts fields so that they are just the numerator values. Not sure where to store the denominator (out of x points)
## Added fields in taxonomy (values in "Self-Reported" tab of google sheet) 
- Licensed enrollment - 'field_licensed_enrollment' 
- Actual enrollment - 'field_actual_enrollment'
- Number of children receiving subsidy - 'field_subsidy_enrollment'
- Number of children with special needs - 'field_special_enrollment'

I think that should be it. I've done a bit of double checking to make sure things are in order. I am sure that there will be issues and questions.

**Comment by bnchdrff** [comment]
Added new fields to feature.

> * Fixed the pts fields so that they are just the numerator values. Not sure where to store the denominator (out of x points)

Can you add the denominators as additional columns in the dataset? Or alternatively can you also post the raw dataset -- i can make an importer that does the work.

**Comment by bnchdrff** [comment]
importer notes:

- convert 'n years n months' field to months & @anderoy will spot check

**Comment by bnchdrff** [comment]
oops, problem! @anderoy can i get a list of the 141 centers which should have a profile created? ideally with the license number?

**Comment by anderoy** [comment]
They should be in the final data file that I sent you.

**Comment by bnchdrff** [comment]
awesome! so the "Self-Reported" tab in https://docs.google.com/spreadsheets/d/1smYR13Ge7YSMgPBoLrfQn3nG2wNA8kKeT5m-x8ITVoA/edit#gid=1007558427 is a safe & final reference?

**Comment by anderoy** [comment]
No, it would be in the file that I emailed to you that has the final
scorecard data.

**Comment by anderoy** [comment]
Here:
[final_scorecard_data 04032015.xlsx | uploaded via ZenHub](https://files.zenhub.io/5523f4220f232ce407726f79)

**Comment by bnchdrff** [comment]
ah, perfect. thx.

**Comment by bnchdrff** [comment]
just finished documenting all newly-added fields in https://docs.google.com/spreadsheets/d/1smYR13Ge7YSMgPBoLrfQn3nG2wNA8kKeT5m-x8ITVoA/edit#gid=0 at bottom of sheet

working on ec migration.

**Comment by bnchdrff** [comment]
Running into some issues getting `name` field set in the `ec` migration, will continue tomorrow!

**Comment by bnchdrff** [comment]
https://www.drupal.org/node/2409695 resolved one of our issues! yay! pegged addressfield_phone version in our project.make just in case.

**Comment by bnchdrff** [comment]
It's all fun and games until you hit a Google API rate limit! We'll need to throttle the import when we push to live...

**Comment by bnchdrff** [comment]
all ec & ec_prpfile migration classes are complete!

now, onto testing the API for these (& possibly whipping up a better scheme for the api in general)

and then, defining the new earlychild data table.

**Comment by bnchdrff** [comment]
imported all data on dev site:

```
$ drush mi GS_ec_terms
Processed 2742 (2705 created, 37 updated, 0 failed, 0 ignored) in 299.3 sec (550/min) - done with 'GS_ec_terms'                           [completed]
$ drush mi ESD_ec_profiles_2015
Processed 140 (140 created, 0 updated, 0 failed, 0 ignored) in 2.3 sec (3632/min) - done with 'ESD_ec_profiles_2015'                      [completed]
$ drush mi GS_ec_profiles
Processed 2742 (0 created, 138 updated, 0 failed, 2604 ignored) in 22.9 sec (361/min) - done with 'GS_ec_profiles'                        [completed]
$ drush mi ESD_oldearlychild_ec_profiles
Processed 138 (0 created, 138 updated, 0 failed, 0 ignored) in 12.1 sec (686/min) - done with 'ESD_oldearlychild_ec_profiles'             [completed]
```

Query the early childhood data:

```
curl --data '{"vid":"19","load_entities":"1"}' --header 'Content-type: application/json' 'https://2015scorecard-3mhev6qb5ihtc.us.platform.sh/api/1.0/taxonomy_vocabulary/getTree.json/' | python -mjson.tool | less
```

**Comment by bnchdrff** [comment]
For now, I think it'd be wise for dev work to query our 2015scorecard dev instance -- we can still run the importer on the live site, but just in case we want to make changes in the API for the benefit for the other devs, we can have them query the easily-changeable site.

**Comment by anderoy** [comment]
Modified a few of the Early Learning Profile field widgets from auto-complete to check list

Also adding Bernita as a user as she will be calling programs to get this additional data filled in. 

If we want to add a program director can I just add a "school representative" user or do we have a different way to do this? If not, that is okay I just wanted to double check in case any of the directors would like access.

**Comment by bnchdrff** [comment]
As soon as I run the migrations on the live site, ESD people like Bernita can begin adding data.

I haven't defined roles or access permissions speific to early childhood information yet -- I can do so this afternoon.

**Comment by bnchdrff** [comment]
full ec_state_ratings schema: 27153c5a196a2771f5c2f204244ea6434ddc008b

started on api, will finish tomorrow morning

**Comment by bnchdrff** [comment]
changed environment & meals fields to term refs & created those taxonomies: dcd560ef25e95971f25a293c555b7a2cb74a567e

**Comment by bnchdrff** [comment]
pulled 2015scorecard branch into live site!

letting data migrations run overnight .. will check in & finish up tomorrow morning

**Comment by bnchdrff** [comment]
actually it's all done :smiley:

**Comment by anderoy** [comment]
The view is: Early Learning Programs

https://2015scorecard-3mhev6qb5ihtc.us.platform.sh/early-learning-programs

The link is : Manage Early Learning Programs on the Logistics Coordinator menu

**Comment by bnchdrff** [comment]
Awesome, it's in the feature now :yum:

**Comment by bnchdrff** [comment]
Added permission `Early Childhood Center Profile: Edit any content` to role `Logistics Coordinator` -- this should do the trick for now, until we define more comprehensive access control for this new system.

**Comment by bnchdrff** [comment]
Also, synced data & code from the live portal back into 2015scorecard... I'll do this after every sprint.

**Comment by bnchdrff** [comment]
```
11:17:04 - me: any clue why FamilyCommunity_Rating appears twice in the esd_el_2015 source spreadsheet?                              
11:17:15 - me: final scorecard data 04032015                                                                                         
11:18:12 - Eric Anderson/gmail.C553BA5F: Ahhhhh                                                                                      
11:18:17 - me: the columns have different values, to boot :)                                                                         
11:18:30 - Eric Anderson/gmail.C553BA5F: to those 4 columns we should add Staff to it                                                
11:18:42 - Eric Anderson/gmail.C553BA5F: FamilyCommunity_Staff_Rating                                                                
11:18:45 - me: ok                                                                                                                    
11:18:52 - me: which 4?                                                                                                              
11:18:56 - me: the first or second set                                                                                               
11:19:02 - Eric Anderson/gmail.C553BA5F: AG to AF                                                                                    
11:19:13 - me: ok                                                                                                                    
11:19:22 - Eric Anderson/gmail.C553BA5F: I mean AG to AJ                                                                             
11:19:25 - me: ok                                                                                                                    
11:19:27 - me: cool                                                                                                                  
11:19:37 - me: i'm going to make the change on my end & upload the file                                                              
11:19:39 - Eric Anderson/gmail.C553BA5F: The second set which belong to the staff survey                                             
11:19:45 - Eric Anderson/gmail.C553BA5F: cool                                                                                        
11:20:47 - me: thanks!                                               
```

**Comment by bnchdrff** [comment]
import seems alright:

```
mysql> LOAD DATA INFILE "/tmp/final_scorecard_data_04032015.csv" INTO TABLE esd_el_2015 COLUMNS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
Query OK, 140 rows affected, 846 warnings (0.01 sec)
Records: 140  Deleted: 0  Skipped: 0  Warnings: 846

mysql> show warnings;
+---------+------+-------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                             |
+---------+------+-------------------------------------------------------------------------------------+
| Note    | 1265 | Data truncated for column 'PhysicalEnviron_Staff_Average' at row 1                  |
| Note    | 1265 | Data truncated for column 'FamilyCommunity_Staff_Average' at row 1                  |
| Note    | 1265 | Data truncated for column 'CulturalLinguistic_Staff_Average' at row 1               |
| Note    | 1265 | Data truncated for column 'CultureClimate_Staff_Average' at row 1                   |
| Warning | 1366 | Incorrect decimal value: '' for column 'teacher_score_mean_2014' at row 1           |
| Warning | 1262 | Row 1 was truncated; it contained more data than there were input columns           |
| Note    | 1265 | Data truncated for column 'PhysicalEnviron_Staff_Average' at row 2                  |
| Note    | 1265 | Data truncated for column 'FamilyCommunity_Staff_Average' at row 2                  |
| Note    | 1265 | Data truncated for column 'CulturalLinguistic_Staff_Average' at row 2               |
| Note    | 1265 | Data truncated for column 'CultureClimate_Staff_Average' at row 2                   |
| Note    | 1265 | Data truncated for column 'teacher_score_mean_2014' at row 2                        |
| Warning | 1262 | Row 2 was truncated; it contained more data than there were input columns           |
| Warning | 1366 | Incorrect decimal value: '' for column 'PhysicalEnviron_Staff_Average' at row 3     |
| Warning | 1366 | Incorrect decimal value: '' for column 'FamilyCommunity_Staff_Average' at row 3     |
| Warning | 1366 | Incorrect decimal value: '' for column 'CulturalLinguistic_Staff_Average' at row 3  |
| Warning | 1366 | Incorrect decimal value: '' for column 'CultureClimate_Staff_Average' at row 3      |
| Note    | 1265 | Data truncated for column 'teacher_score_mean_2014' at row 3                        |
| Warning | 1262 | Row 3 was truncated; it contained more data than there were input columns           |
| Note    | 1265 | Data truncated for column 'PhysicalEnviron_Staff_Average' at row 4                  |
| Note    | 1265 | Data truncated for column 'FamilyCommunity_Staff_Average' at row 4                  |
| Note    | 1265 | Data truncated for column 'CulturalLinguistic_Staff_Average' at row 4               |
| Note    | 1265 | Data truncated for column 'CultureClimate_Staff_Average' at row 4                   |
| Note    | 1265 | Data truncated for column 'teacher_score_mean_2014' at row 4                        |
| Warning | 1262 | Row 4 was truncated; it contained more data than there were input columns           |
| Warning | 1366 | Incorrect decimal value: '' for column 'PhysicalEnviron_Staff_Average' at row 5     |
| Warning | 1366 | Incorrect decimal value: '' for column 'FamilyCommunity_Staff_Average' at row 5     |
| Warning | 1366 | Incorrect decimal value: '' for column 'CulturalLinguistic_Staff_Average' at row 5  |
| Warning | 1366 | Incorrect decimal value: '' for column 'CultureClimate_Staff_Average' at row 5      |
| Note    | 1265 | Data truncated for column 'teacher_score_mean_2014' at row 5                        |
| Warning | 1262 | Row 5 was truncated; it contained more data than there were input columns           |
| Note    | 1265 | Data truncated for column 'PhysicalEnviron_Staff_Average' at row 6                  |
| Note    | 1265 | Data truncated for column 'CulturalLinguistic_Staff_Average' at row 6               |
| Warning | 1264 | Out of range value for column 'Published_QRIS_Rating_2014' at row 6                 |
| Warning | 1366 | Incorrect decimal value: '' for column 'teacher_score_mean_2014' at row 6           |
| Warning | 1262 | Row 6 was truncated; it contained more data than there were input columns           |
| Note    | 1265 | Data truncated for column 'FamilyCommunity_Staff_Average' at row 7                  |
| Note    | 1265 | Data truncated for column 'CulturalLinguistic_Staff_Average' at row 7               |
| Warning | 1366 | Incorrect decimal value: '' for column 'teacher_score_mean_2014' at row 7           |
| Warning | 1262 | Row 7 was truncated; it contained more data than there were input columns           |
| Warning | 1366 | Incorrect decimal value: '' for column 'PhysicalEnviron_Staff_Average' at row 8     |
| Warning | 1366 | Incorrect decimal value: '' for column 'FamilyCommunity_Staff_Average' at row 8     |
| Warning | 1366 | Incorrect decimal value: '' for column 'CulturalLinguistic_Staff_Average' at row 8  |
| Warning | 1366 | Incorrect decimal value: '' for column 'CultureClimate_Staff_Average' at row 8      |
| Note    | 1265 | Data truncated for column 'teacher_score_mean_2014' at row 8                        |
| Warning | 1262 | Row 8 was truncated; it contained more data than there were input columns           |
| Note    | 1265 | Data truncated for column 'PhysicalEnviron_Staff_Average' at row 9                  |
| Note    | 1265 | Data truncated for column 'CulturalLinguistic_Staff_Average' at row 9               |
| Note    | 1265 | Data truncated for column 'CultureClimate_Staff_Average' at row 9                   |
| Warning | 1366 | Incorrect decimal value: '' for column 'teacher_score_mean_2014' at row 9           |
| Warning | 1262 | Row 9 was truncated; it contained more data than there were input columns           |
| Note    | 1265 | Data truncated for column 'PhysicalEnviron_Staff_Average' at row 10                 |
| Note    | 1265 | Data truncated for column 'FamilyCommunity_Staff_Average' at row 10                 |
| Note    | 1265 | Data truncated for column 'CultureClimate_Staff_Average' at row 10                  |
| Warning | 1264 | Out of range value for column 'Published_QRIS_Rating_2014' at row 10                |
| Warning | 1366 | Incorrect decimal value: '' for column 'teacher_score_mean_2014' at row 10          |
| Warning | 1262 | Row 10 was truncated; it contained more data than there were input columns          |
| Warning | 1366 | Incorrect decimal value: '' for column 'PhysicalEnviron_Staff_Average' at row 11    |
| Warning | 1366 | Incorrect decimal value: '' for column 'FamilyCommunity_Staff_Average' at row 11    |
| Warning | 1366 | Incorrect decimal value: '' for column 'CulturalLinguistic_Staff_Average' at row 11 |
| Warning | 1366 | Incorrect decimal value: '' for column 'CultureClimate_Staff_Average' at row 11     |
| Note    | 1265 | Data truncated for column 'teacher_score_mean_2014' at row 11                       |
| Warning | 1262 | Row 11 was truncated; it contained more data than there were input columns          |
| Note    | 1265 | Data truncated for column 'PhysicalEnviron_Staff_Average' at row 12                 |
| Note    | 1265 | Data truncated for column 'FamilyCommunity_Staff_Average' at row 12                 |
+---------+------+-------------------------------------------------------------------------------------+
```

**Comment by bnchdrff** [comment]
actually untrue... spec'ing NULL values

**Comment by bnchdrff** [comment]
@anderoy what's the value for row 18 column AR supposed to be?

**Comment by anderoy** [comment]
It says -1.

They range from -1 to 5. If needed you can change all -1s in that column into NULL values.

**Comment by bnchdrff** [comment]
excellent -- thanks!

**Comment by bnchdrff** [comment]
Added esd_el_2015 data table & view

Eric, do you want to add docs to https://github.com/ESDet/esdportal_str/wiki/datasets__esd_el_2015 ?

**Comment by bnchdrff** [comment]
Also, for the record.. I uploaded the slightly normalized "final_scorecard_data_04032015" data csv to https://drive.google.com/drive/u/0/folders/0B7QdNmEHvwalNUpIOWU2ckVaVmM/0B7QdNmEHvwalflN1Q1pZd0xNM0I4QXNQYlFRYmVYdmo2bTVHSEtkTmtrQ1hsRXVaSE1nNGc/0B9LDi9SHMwnrRjF3WTNGcWRvRWc/0B9LDi9SHMwnrfmExUTQ4SVhjSENpaXhzekFQaWV3Q0hHSFhKLTFoSG9VajkwU0dDb0JvalU

**Comment by bnchdrff** [comment]
added `describe esd_el_2015` output to that wiki page, as a temp reference.
