### ISSUE TITLE
Mobile improvements

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#31]
Increase menu size on mobile.

Also, three options:

* Logo smaller (Just the Portal)
* Make the menu accordion style collapse
* Hamburger menu with pull-in menu

**Comment by anderoy** [comment]
Here is a smaller image that can be used for the mobile responsive design. I see it being right-aligned and inline with the Hamburger icon left-aligned.

![esd_portal_logo_mobile](https://cloud.githubusercontent.com/assets/603548/10317457/7fac3a78-6c32-11e5-962d-df69fc2f0405.png)

I think this module will work best for easily creating the mobile responsive menu (it says it works with Context): https://www.drupal.org/project/responsive_menus

**Comment by bnchdrff** [comment]
decided to use the mobile menu that i developed for the original ESD homepage -- works great on phones & you even get the native iPhone scrollie thing!

**Comment by anderoy** [comment]
The logo is still taking up too much space at the top of the page and the mobile menu thing is a bit weird. The width spacing on the orange link is too short and with the large green "Coach Menu" that doesn't do anything, it still takes up too much screen space.

![screenshot_2015-10-15-09-21-04](https://cloud.githubusercontent.com/assets/603548/10514840/5270f59c-731e-11e5-88c6-975bc85a27a7.png)

If we are going to use your style of mobile menu, I would prefer it to be limited to the Green Box that says "Coach Menu" with a green arrow. That would open your scrollie thing. With that and a reduced header logo image, we will be in business.
