### ISSUE TITLE
Fix views integration for e3_contact

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#34]
only lastname shows up, no firstname
weird non-basetable properties are included as well (description)

**Comment by gl2748** [comment]
Possible Typos:
Search for description, 
Cf. Lastname vs Firstname regarding views

**Comment by anderoy** [comment]
@gl2748 and @bnchdrff

 I also commented on the commit, but can this be pushed to https://29-e3teachers-3mhev6qb5ihtc.us.platform.sh without affecting the changes that I have been working on slowly?

**Comment by gl2748** [comment]
@anderoy 
This is not quite ready to be pushed because the issue may be related to the VBO integration issue. Working on this today and will keep you posted.

**Comment by bnchdrff** [comment]
these fields should be hidden on the edit form
