### ISSUE TITLE
VBO doesn’t seem to work with the base table properties on new entities

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#37]
. (for example it would have been beneficial to bulk assign teachers to a coach/author)

**Comment by gl2748** [comment]
VBO cannot modify properties on the entity. VBO, API integration to do. Assuming VBO will have docs on how to integrate it with your own custom entity.

**Comment by anderoy** [comment]
So ok, the "Change the coach." operation works. But when I tried to "Modify Entity Values" (after re-adding in to the VBO menu), it will take me through the process and have the appearance that it made the changes, but when I go into the actual Contact/Teacher entity, nothing has changed.

**Comment by bnchdrff** [comment]
Modify Entity Values will not work -- this is why we created "Change the coach" -- this is a bug in VBO unfortunately.

**Comment by anderoy** [comment]
Ahh, I wish I would have understood this better. When you discussed this I thought that you were trying to fix the VBO bug. I didn't know that you were spending time implementing ONLY the coach thing. This was a really low ROI and somewhat pointless without it having fixed the modify entity values bug.

Win some, lose some.

**Comment by bnchdrff** [comment]
We can add any/all other entity properties if needed -- that part is quick now that the initial work is done.

**Comment by gl2748** [comment]
Yes, Eric which entity value are you trying to change?

**Comment by anderoy** [comment]
It doesn't really matter which value I am trying to change at this point. I would like to be able to change all of them.

This gets to our internal data management needs. EITHER vbo works OR editable fields works. Right now, neither of them do. This means that in order to modify fields for all teachers, I have to go in one by one and edit their info.

This--I would have thought was clear by now--is essential and has always worked with fields everywhere else on the site.

**Comment by anderoy** [comment]
But if you need an example of what I am trying to manage/change right now (which is not the only thing I will ever want to mass edit) I am trying to add data to the new training fields that were added to the teacher contact.

**Comment by anderoy** [comment]
I think that fixing the Editable Fields ASAP (no later than the 28th deadline) would be the right solution for ESD needs.

**Comment by bnchdrff** [comment]
Great, we'll work on #35!

**Comment by bnchdrff** [comment]
Fixed in https://github.com/ESDet/esdportal_e3/commit/1fd965e54c140e13f8ee7517d6e011ffe5cdd696 & pushed to live portal

**Comment by bnchdrff** [comment]
Field API fields are now modifiable via Views VBO "Modify entity values" action. Please review!

**Comment by gl2748** [comment]
@bnchdrff did this not work out ben? The solution was to add:
```
case 'update' :
case 'delete' :
```
to `function e3_contact_access()` and `function e3_note_access()`

**Comment by bnchdrff** [comment]
The fix is up on production for eric to review.

**Comment by anderoy** [comment]
I must not be using the correct branch. Still nothing is changing. See link below and try to modify Status and Cohort (as an example):
https://29-e3teachers-3mhev6qb5ihtc.us.platform.sh/e3-teachers

**Comment by anderoy** [comment]
NI deleted my previous comment. This guy needs to remember the difference between, development, staging, and production.

Got it, checked it out. Looks and works great. This and the editable fields. Thanks guys!
