### ISSUE TITLE
Add 2015 k12 datasets

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#4]

**Comment by bnchdrff** [comment]
please specify which datasets to add & link to csvs

**Comment by anderoy** [comment]
@bnchdrff How much trouble  (billable time) would it be to change 3 field names and their "labels" and delete 3 fields from the HS schema.

Then change one field name in the K8 schema?

**Comment by bnchdrff** [comment]
An hour probably... also will involve frontend changes possibly.

**Comment by anderoy** [comment]
Talked to Alec and it doesn't look like the front-end changes on these modification will be significant (if at all)

**Comment by anderoy** [comment]
The only changes come at the end of each dataset. I will start with the easy change:
## esd_k8_2015
DELETE net5e_pts
CHANGE net5e TO cat5e

Now the more challenging. One field per line.
## esd_hs_2015
CHANGE cepi_uncond_enroll_5yr_mme TO col_enr_pct AND LABEL "College Enrollment Among MME Takers Conditional on 5-Year Graduates (2013, 2014 2-Year Average)"
col_persist_pts	 STAYS THE SAME
CHANGE cepi_cond_coll_persist TO col_persist_pct AND LABEL "College Persistence Conditional on College Enrollment (2012, 2013 2-Year Average)"
DELETE fouryr_col_enr_pts
DELETE cepi_uncond_enroll_4yr_mme
DELETE net5e_pts
CHANGE net5e TO cat5e

**Comment by anderoy** [comment]
@bnchdrff You can make the changes listed above.

I am once again awaiting our Data Analyst to give me back the files with State and Detroit Averages (which are vital to the Scorecard Display). He said he would have them to me today. I will post them here as soon as possible.

**Comment by anderoy** [comment]
So assuming that the above changes are made here are the datasets to be loaded to the site.

esd_k8_2015
https://drive.google.com/open?id=0B9LDi9SHMwnrTXhuSWRva0dLd3c&authuser=0

esd_hs_2015
https://drive.google.com/open?id=0B9LDi9SHMwnrZEw1d0NDcS1QSDg&authuser=0

**Comment by bnchdrff** [comment]
changes made, datasets LOADed & pushed to live.

cool test url: https://portal.excellentschoolsdetroit.org/api/1.0/schools.json?limit=133&flatten_fields=true&filter_special=school_profile_collegereadiness&includes=school_profile,esd_k8_2015,esd_hs_2015
