### ISSUE TITLE
Add Duration fields to Session Log and Observation Log bundles

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#40]
This field will store the computed value of the difference between the start and end date fields.

Not needed on the CLASS Assessment bundle.

**Comment by bnchdrff** [comment]
Store as an integer with unit "minutes"

**Comment by gl2748** [comment]
Drupal field example - have a look at it. 
https://www.drupal.org/node/1331046#comment-5350042

**Comment by anderoy** [comment]
This field doesn't seem to be calculating at all.

**Comment by bnchdrff** [comment]
We never actually worked on this issue -- we decided to move it to a backlog and tackle other features instead -- should it still be done?

**Comment by bnchdrff** [comment]
Ah, nevermind -- this should've been fixed in https://github.com/ESDet/esdportal_e3/commit/22b8dba40eb8b8c3ec076194f0ca0ebd47e5f7f9

**Comment by bnchdrff** [comment]
Looking into it.

**Comment by bnchdrff** [comment]
Fixed; will deploy along with the current batch of scorecard work.
