### ISSUE TITLE
Use menu tabs for all these links

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#42]
For example, the "Back to Teacher List" and "Add Log Entry" links at the teacher-report/1 view display.

**Comment by gl2748** [comment]
http://cgit.drupalcode.org/examples/tree/menu_example/menu_example.module

**Comment by gl2748** [comment]
For some reason tabs are not displaying on the view at teacher-report/1/1.
For example in hooK_menu, this works (i.e. a tab appears at `node/1`):
```

  $items['node/%/some_action'] = array(
    'title' => 'This Is A new Tab',
    'page callback' => 'esdportal_e3_some_action_tab',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
```
This does not work (i.e. no tab appears at: `teacher-report/1/1`)
```
  $items['teacher-report/1/%/some_action'] = array(
    'title' => 'This Is A new Tab',
    'page callback' => 'esdportal_e3_some_action_tab',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
```

**Comment by gl2748** [comment]
ToDo:
* Bonus: Enable prepopulate module and pass teacher id to 'add observation log' form.
* Correct permissions for these links, as they are currently too broad.
* From my understanding there should be a 'Back to teacher list' link - but I am not 100% this is required, so have not added it.
