### ISSUE TITLE
Live Push from 10/14 Sprint/Crawl

### ISSUE THREAD

**Issue by anderoy** [ESDet/esdportal_profile#44]
As we have discussed in a separate issue #39 we will accept an interim fix on the calculated fields. The following was the work I did that needs to be added to the live site. Check off boxes if it is included in the push. Thanks.

- [x] Modify e3-teachers view
- [x] added data export that inherits exposed filters
- [x] Modify e3-logs view
- [x] Heavily Modify teacher-report view
- [x] Add 10x2 dimension “sub-pages’ with two attachment tables that contextually filter to the sub-page dimension.
- [x] Add Early Childhood parent organization Taxonomy Vocab, add a few terms (are these in the database or code?), add as field to Early Childhood center Vocab
- [x] Change “Data Entry” role to “E3 Admin” and modify permissions
only person currently on “Data Entry” is Bernita (who just so happens to be an E3 Admin). We don’t need the data entry role as it existed anymore.
- [x] Add E3 Admin Menu
- [x] Add E3 Admin Context
- [x] Modify CLASS Assessment with new fields to be used with “Calculated Fields”
- [x] Enable Views Flipped Table
- [x] Add E3 Tracker Fieldset and additional fields to Teacher Contact
- [x] Deleted fields from CLASS Assessment and cleaned up CLASS Ave view (deleted non-existent fields and de-attached from page)

**Comment by bnchdrff** [comment]
* removed eck references & added settings for new e3 entity types
* renamed permissions for data entry role to E3 Admin
* added E3 Admin role to esdportal_str
* added e3 admin context & menu to esdportal_e3_feature
* added  Early Childhood parent organization vocabulary -- terms should be in database if they will be changing often
* added `taxonomy_term-ec_parent_organization-field_contact_person` field to ec_parent_organization vocab bundle
* added many fields to e3 teacher bundle:
```
e3_contact-teacher-field_e3_cohort
e3_contact-teacher-field_e3_status
e3_contact-teacher-field_training_attendance
e3_contact-teacher-field_training_hours_f1
e3_contact-teacher-field_training_hours_f2
e3_contact-teacher-field_training_hours_f3
e3_contact-teacher-field_training_hours_m1
e3_contact-teacher-field_training_hours_m2
e3_contact-teacher-field_training_hours_s1
e3_contact-teacher-field_training_hours_s2
e3_contact-teacher-field_training_hours_total
e3_contact-teacher-field_training_hours_w1
e3_contact-teacher-field_training_hours_w2 
```

**Comment by bnchdrff** [comment]
merging into the field-calculation branch & will push to live with those bugfixes after that's done

**Comment by bnchdrff** [comment]
merged in 65095df1a557440f7e1aa71b1c8d94af8e81edaa

eric, i'm not sure what "Add 10x2 dimension “sub-pages’ with two attachment tables that contextually filter to the sub-page dimension." is referring to - is this a view contained in the feature already?

for " Change “Data Entry” role to “E3 Admin” and modify permissions only person currently on “Data Entry” is Bernita (who just so happens to be an E3 Admin). We don’t need the data entry role as it existed anymore." we'll need to make the user role changes manually when we push to live.

**Comment by anderoy** [comment]
The 10x2 pages are just different pages I added to the E3 Teacher Report view. If you look at the view ui page for that you will see what I mean. If you committed my changes to code, based on the changes I made to the views, it should be there.

**Comment by anderoy** [comment]
PC, PC Line, NC, NC Line (for example)

**Comment by anderoy** [comment]
I ended up needing to make a few "hotfixes" or minor adjustments to a few things on the live site in order to get things cleaned up a bit. Here are the changes:

- Added links to E3 Admin menu
- Edit E3 Teacher Reports view
-- changed permissions (added E3 Admin)
-- added fields and modified CLASS Ave
-- added fields to Domains
- Edit E3 Teacher Management view
-- Edit link rewrite
-- Make a few table columns sortable
- Edit E3 Log Management view
-- Set default sort descending date created
- Edit CLASS Assessment display (hide the cycles)
