### ISSUE TITLE
By Saturday morning: Document & add fields to e3-note bundles and views; document any required calculated fields

### ISSUE THREAD

**Issue by anderoy** [ESDet/esdportal_profile#46]
I need to add another E3 Experience Note type that is similar to--but not the same as--the CLASS Assessment. The unfortunate reality of this is that it will likely require new calculated fields. Can you add a step-by-step checklist of how we can do this as quickly as possible while also requiring as little of your time as possible? Thank you.

**Comment by bnchdrff** [comment]
Can you document the required functionality for me to review?

Part of this should be documenting the functionality of the CLASS Assessment as it's currently implemented; the spec doc is out of date. I can help with this if you'd like.

**Comment by anderoy** [comment]
I am not sure what you exactly mean by documenting the functionality of the CLASS Assessment.

I basically need to add a new "E3 Experience Note" Bundle called CLASS Assessment (Infant & Toddler) that will have the same base properties as the other E3 Experience Notes. I will need to add fields for the new "Dimensions" (4 cycles per Dimension and a Notes field) and then will need you to create the Dimension and Domain averages based on a different calculation that I will add here in a separate comment.

Then I will basically clone and edit the "Domains" and "CLASS Ave" attachments in the Teacher Report view so that the CLASS Baseline information on the teacher report page will look different for teachers based on which CLASS Assessment was performed.

Deadline for this will be next week Tuesday 11/10.

**Comment by anderoy** [comment]
I assume that you will want me to add the new CLASS Assessment and other changes on a Dev site. To make sure that I am building it in a way that works for coaches, I think a fresh dev environment would be necessary so I created Issue #47

**Comment by bnchdrff** [comment]
By documenting the CLASS Assessment, I mean that we need to document the recently-implemented functionality -- those changes were rushed & ended up being very, very different from the original plans. If we don't document them, and they get broken later, we won't know how to fix them. Also, if other developers join the project, they will have an easier time understanding how things work if we have documentation.

Have you defined how the new infant/toddler bundle would work?

**Comment by anderoy** [comment]
Yeah, we aren't building software as a static or perfect dream that can be fully visioned and painted on a canvas to be reveled at. The original plans were based on a few months of solid requirements gathering from a group that didn't even really know what they wanted. Once we built it, we needed to make modifications to better suit the needs of the people who we were building the software for.

I thought that I defined how it will work in the third comment above, but here is another go:

1. Coach clicks link add CLASS Assessment (I/T)
2. Coach adds information as shown in attached form (similar to previous CLASS Assessment)
3. After clicking save, Dimension averages and Domain averages are calculated and displayed.
4. Coach will be able to see CLASS averages and scores on Teacher Report Page.
5. Coach has ability to view and edit logs for their teachers (added as mod to live site).

Ultimately, it will be best for me to add all of the fields, then have you add the fields to calculate the averages, then I build the view, and done.

[CLASS Infant Toddler Info.pdf](https://github.com/ESDet/esdportal_profile/files/28889/CLASS.Infant.Toddler.Info.pdf)

**Comment by anderoy** [comment]
All changes to the e3-note bundles have been made and documented: https://docs.google.com/document/d/1L3WWBA_Y7HMr4k_GL7PZTrpHj3mWyUO9YsrKBa_whz4/edit#heading=h.jyfvx09pb0ee

In order for me to move forward and complete the required view, I will need the calculated fields to be built in to class_assessment_it as follows:
'field_rc_average = The average of all COMPLETED rc_cycle fields'
'field_tsit_average = The average of all COMPLETED ts_cycle fields'
'field_fe_average = The average of all COMPLETED fe_cycle fields'
'field_els_average = The average of all COMPLETED els_cycle fields'
These can be placed before their respective xx_notes fields.
'field_rspc_score = average of the four above averages'
This can have a label of Responsive Caregiving Score.

**Comment by bnchdrff** [comment]
all set! see sample data at https://48-e3noteit-3mhev6qb5ihtc.us.platform.sh/e3-note/102

**Comment by anderoy** [comment]
All set on my end now. I modified the teacher-report view pretty significantly, and it is all documented in the doc (link below). I mainly added the I/T stuff and then cleaned up the Count/Menu attachment to be a bit more space friendly (hide rows with no observations).

I also modified a few things in the taxonomy vocabularies to add some important fields that we are in need of storing for Early Childhood common enrollment work:
- deleted a few unnecessary things
- added a few new vocabulary items
- added 5 fields to ec vocab
See the documentation of this following the documentation of the view changes

https://docs.google.com/document/d/1L3WWBA_Y7HMr4k_GL7PZTrpHj3mWyUO9YsrKBa_whz4/edit#heading=h.jyfvx09pb0ee

**Comment by anderoy** [comment]
I added a new field to the ec taxonomy vocabulary that was supposed to be included by I forgot about until now. Added it in the doc and on the dev site. Looks like this hasn't been done so I am assuming that it is an acceptable addition. Thanks.

**Comment by bnchdrff** [comment]
Looks like parent organization is no more? Just want to double-check.

**Comment by anderoy** [comment]
Correct.
