### ISSUE TITLE
By Friday morning: Commit hot fixes to code & spin up new dev environment

### ISSUE THREAD

**Issue by anderoy** [ESDet/esdportal_profile#47]
It seems like there are always things that get left behind every time we push changes from the dev site to the live site. This has forced me to make hotfixes to the live site to make sure that everything works for coaches and for our internal data management.

Is it possible to commit all changes that have been made to the live site to code, then set up a dev environment that is an exact copy of the live site as it exists in it's current state since it currently works the way we need it to?

**Comment by bnchdrff** [comment]
The only way to ensure that changes are successfully merged into live from a development environment is to capture them in code and to do a test deployment where we can assure the quality of all the modificaitons by comparing them to a specifications document.

I can commit changes made on live to code by cloning the live environment locally and selecting customizations that need to be defined in code -- what changes have been made?

**Comment by anderoy** [comment]
You can see the views where it says "Database overriding code" in the image below. I don't know how specific you need me to detail my changes. The main thing is to make sure the three E3 views are in code as currently implemented in the live site.

![image](https://cloud.githubusercontent.com/assets/603548/10998858/4808d364-8466-11e5-90de-8d767e728623.png)

**Comment by bnchdrff** [comment]
* committed all hotfixes & pushed to master
* deactivated `29-e3teacher` & `8-ec-ratings` environments
* created new environment `48-e3noteit` https://48-e3noteit-3mhev6qb5ihtc.us.platform.sh/

e3 views changes seem to all be captured in code -- see https://github.com/ESDet/esdportal_e3/commit/cd551898bc6f8f3efd18bc53ab7d8fe0ec777f03#diff-adeffb499399b9b861bdb23544edd05bL32 for details
