### ISSUE TITLE
Add proximity search options to schools API endpoint

### ISSUE THREAD

**Issue by bnchdrff** [ESDet/esdportal_profile#50]

**Comment by bnchdrff** [comment]
Deployed to dev site

See https://50-proximity-3mhev6qb5ihtc.us.platform.sh/developers/schools#schools-index for docs

Sample queries:

Some schools within 1 mile of Horatio & Livernois: https://50-proximity-3mhev6qb5ihtc.us.platform.sh/api/1.0/schools.json?limit=50&near_latlon=42.336052,-83.123111&near_miles=1

Some schools within 5 miles Plymouth & Evergreen: https://50-proximity-3mhev6qb5ihtc.us.platform.sh/api/1.0/schools.json?limit=500&near_latlon=42.371924,-83.236356&near_miles=5

**Comment by bnchdrff** [comment]
As an example, I've set up a simple geocoder service; example query: https://50-proximity-3mhev6qb5ihtc.us.platform.sh/api/1.0/geocoder/google?data=2+Woodward+Ave+Detroit+MI+48226

@uniosx this seem ok?

For production it'd probably be wise to enable some sort of auth for this, though...

**Comment by bnchdrff** [comment]
n.b. u can specify format as described at https://50-proximity-3mhev6qb5ihtc.us.platform.sh/api/1.0/geocoder.yaml

**Comment by anderoy** [comment]
Looks good on basic testing and usage on Scorecard.
