### ISSUE TITLE
Refine Existing Search Parameters

### ISSUE THREAD

**Issue by anderoy** [ESDet/esdportal_profile#53]
Referencing the code here: https://github.com/ESDet/esdportal_api/blob/7.x-1.x/esdportal_api.module

- Lower the Arts requirement to 3 total, change comment in line 1524 to 3
- [x] Line 1561 change 8 to 2

- Lower the Sports requirement to 3 or more Change comment in lines 1575 and 1576
- [x] Lines 1590 and 1597 change 3 to 2

In a quick review of the API, those are what I came up with

**Comment by anderoy** [comment]
Somewhere in the code at lines 1793 and 1852 it looks like there is the sort options for the early programs.

`total_points` needs to be a secondary sort applied after an `overall_rating` of Gold, Silver, Bronze. The way the ratings work, it is possible for a program to not receive a medal in `overall_rating` and yet have a greater `total_points` value than a program that received a "Bronze" medal in `overall_rating`.

Just want to make sure that it is working that way.

**Comment by bnchdrff** [comment]
I've made the two changes in the first comment, but haven't pushed them to dev or prod servers yet.

For the second comment, can you describe the way you'd like the results to be sorted with an example?

**Comment by anderoy** [comment]
The changes look good. I'll close this for now as I expect it to work properly once we start testing. On my second comment, I will hold off on that to see how it is actually sorting during the testing.
