### ISSUE TITLE
Early Childhood Program Sorting

### ISSUE THREAD

**Issue by anderoy** [ESDet/esdportal_profile#54]
This query is being used to rank early programs on the scorecard which returns some interesting results.

https://50-proximity-3mhev6qb5ihtc.us.platform.sh/api/1.0/ecs.json?limit=25&offset=0&flatten_fields=true&includes=most_recent_ec_state_rating,ec_profile,esd_el_2015&sort_by_special=ec_state_ratings.total_points&sort_order_special=DESC&filter[field_scorecard_display]=1&filter_special=has_esd_el_2015

This is what it returns:
1. WSU Merril-Palmer...
2. Woodward Academy (Pre-K)
3. White - DPS Foundation...

This is what it should return:

1. C.R. Smith Pre-K Academy
2. Iris Center (Renaissance Head Start)
3. ?? WSU Merril Palmer (maybe)

To look for the top early programs I tried to grab the up-to-date ec_state_ratings from here: https://50-proximity-3mhev6qb5ihtc.us.platform.sh/api/1.0/ec_state_ratings.json then convert to csv and it looks like the fixes to the  that you made were lost, see reopened issue here: https://github.com/ESDet/esdportal_profile/issues/8

Since I thought that was fixed and now it doesn't seem to be, I will hold off on saying that these are the last things for now, but they should be.

**Comment by bnchdrff** [comment]
wrong query: the option is ec_total_pts

https://portal.excellentschoolsdetroit.org/api/1.0/ecs.json?limit=25&offset=0&flatten_fields=true&includes=most_recent_ec_state_rating,ec_profile,esd_el_2015&sort_by_special=ec_total_pts&sort_order_special=DESC&filter[field_scorecard_display]=1&filter_special=has_esd_el_2015

please see docs: https://portal.excellentschoolsdetroit.org/developers/schools#ecs-index

also i'm shutting down the 50-proximity branch as it's merged in!
