### ISSUE TITLE
Schools not returning in API call.

### ISSUE THREAD

**Issue by anderoy** [ESDet/esdportal_profile#55]
So below is an example of an API call that the Scorecard app is making. There is some sort-reordering the app is doing to handle ranking all of the different programs with some extra special exception logic.

Problem is that some schools like Detroit Achievement Academy - tid:2270 aren't showing up in the following API call:

https://50-proximity-3mhev6qb5ihtc.us.platform.sh/api/1.0/schools.json?limit=25&offset=0&flatten_fields=true&includes=school_profile,esd_k8_2016,esd_hs_2016&filter[field_scorecard_display]=1&sort_by_special=school_combined_total_pts&sort_order_special=DESC

Perhaps it is the "New" schools - field_school_scorecard_status=7 that are being left out of the returned values?

**Comment by bnchdrff** [comment]
Detroit Achievement Academy does show up:
https://50-proximity-3mhev6qb5ihtc.us.platform.sh/api/1.0/schools.json?limit=500&offset=0&flatten_fields=true&includes=school_profile,esd_k8_2016,esd_hs_2016&filter%5Bfield_scorecard_display%5D=1&sort_by_special=school_combined_total_pts&sort_order_special=DESC

just not in the first 25 results

**Comment by anderoy** [comment]
Cool, all good.
