### ISSUE TITLE
Timestamp endpoints for caching purposes

### ISSUE THREAD

**Issue by uniosx** [ESDet/esdportal_profile#56]
We're looking to avoid hitting the API for search results when we don't need to. We only want to retrieve all school data from the API if a school has been updated, otherwise we'll use a local cache of the search results. It'd be a big help to have an endpoint for schools and ec where it returns the timestamp of the most recently updated school / center.

**Comment by bnchdrff** [comment]
I'll define two endpoints -- one for ECs, and one for schools. They will respond with the timestamp of the most recently updated entity, whether it's the canonical record or the associated profile.

**Comment by bnchdrff** [comment]
https://portal.excellentschoolsdetroit.org/api/1.0/most_recent_ec_timestamp.json & https://portal.excellentschoolsdetroit.org/api/1.0/most_recent_school_timestamp.json are live!

**Comment by uniosx** [comment]
Thanks for the quick turnaround! I'll test it out.
