### ISSUE TITLE
Spring modifications

### ISSUE THREAD

**Issue by anderoy** [ESDet/esdportal_profile#7]
Made changes to the Spring Modifications branch on Platform (not sure where to put this issue). https://spring-modifications-3mhev6qb5ihtc.us.platform.sh

## Changes made
Changed Display Settings of School Profile
- Hide anything to do with Site Visit and Growth Doc from Display and added to a collapsed fieldset, renamed to "Old Fields (Ignore)"
- Added file upload field (upon Armen's request for there to be a "dropbox" for schools to upload files that they would like to share.
- Removed Tab groups and pulled all active fields to top-level
- Moved the order of some fields in both edit and display mode

Modified "Schools" Vocabulary
- Added field_2015_profile

Modified manage-school-profiles view
- Removed site visit info
- Added 2014 Profile complete
- Added editable 2015 profile complete

Modified Early Childhood Profile
- Added field_ec_cost_prek and field_ec_cost_b4

**Comment by bnchdrff** [comment]
- Merged latest esdportal_str changes from 2015scorecard work into spring modifications branch
- Merged back into 2015scorecard
- Reverted field_group, field_instance, views, and variable
- Testing... looks great.

**Comment by bnchdrff** [comment]
Merged into master!
